#!/bin/sh

mount -o remount,rw /

device="HB-UNI-Sen-CAP-MOIST"
device_img=hb-uni-sen-cap-moist.png
device_thumb=hb-uni-sen-cap-moist_thumb.png
firmware_file=/firmware/rftypes/hb_unisen_capmoist.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch=" $device {{50 \/config\/img\/devices\/50\/$device_thumb} {250 \/config\/img\/devices\/250\/$device_img}} "

if [ "`cat $devdescrFile | grep \"$device\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$device\"`" ]; then
        sed -i "/\($device\)/d" $webuiFile
fi

rm -f $firmware_file
rm -f /www/config/img/devices/250/$device_img
rm -f /www/config/img/devices/50/$device_thumb

sync
mount -o remount,ro /